### ISSUE TITLE
Vecenv with Baselines

### ISSUE THREAD

**Issue by jangirrishabh** [montrealrobotics/domain-randomizer#11]
Hi, great work with the domain randomization implementation !

I was looking at your randomized_vecenv.py script, have you been able to run that with openAI baselines?  I am facing some issues doing the same

Question 2: The update_randomized_params() gets called upon reset? it does not, it's a standalone function

**Comment by bhairavmehta95** [comment]
Unfortunately, this code isn't going to be out-of-box compatible with Baselines. You can take a look at our examples + our ADR implementation to see how to use the library best.

https://github.com/montrealrobotics/active-domainrand
